spring:
  #开发环境配置
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.48.128:3308/tourism?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  mvc:
    view:
      prefix: /templates
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
uploader:
  #开发环境配置   E:\software\ftpserver\file-transform-temp\ffmpeg
  basePath: D:\\tourism\\tourismfileService\\
  ffmpegpath:  D:\\tourism\\tourismfileService\\ffmpeg.exe
  mencoderpath:  D:\\tourism\\tourismfileService\\mencoder.exe
  avifilepath:  D:\\tourism\\tourismfileService\\temp.avi
  displayPath: ${localaddress}:${server.port}/image/
  converMp4: true
  converType: asx,asf,mpg,wmv,3gp,mov,avi,wmv9,rm,rmvb
  tempPath: D:\\tourism\\tourismfileService\\temp
  ftpserver:
    port: 2122
    name: admin
    password: admin
    #homeDirectory: C:\\tourism\\tourismfileService
    ##开发环境配置
    homeDirectory: D:/tourism/tourismfileService/
    path: ftp://admin:admin@127.0.0.1:2122/
beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用
  delimiter-statement-start: \@
  delimiter-statement-end:
beetlsql:
  enabled: false

accessurl: http://127.0.0.1:8080,http://127.0.0.1:80,http://127.0.0.1:8081
localaddress: http://127.0.0.1
codelist: 123456
remote-file: http://127.0.0.1/userfiles/
priview-url: http://127.0.0.1:8012/






